'use strict';
const el=id=>document.getElementById(id);
let verified=false;
async function api(path,body){const res=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
function fields(){const mode=el('operation').value;el('generation').hidden=mode!=='generate';el('source-fields').hidden=mode==='generate';el('animation-fields').hidden=mode!=='animate';}
el('operation').addEventListener('change',fields);
el('balance').addEventListener('click',async()=>{el('balance').disabled=true;try{const b=await api('/api/balance');verified=true;el('account').textContent=`API connection verified. Available balance: ${b.balance ?? 'not returned'}. Frozen: ${b.frozen ?? 'not returned'}.`;el('submit').disabled=false;}catch(e){verified=false;el('submit').disabled=true;el('account').textContent=e.message;}finally{el('balance').disabled=false;}});
el('task-form').addEventListener('submit',async e=>{e.preventDefault();if(!verified)return;el('submit').disabled=true;el('message').textContent='Submitting one task…';try{const data=await api('/api/task',{operation:el('operation').value,prompt:el('prompt').value,model_version:el('version').value,source_task:el('source').value.trim(),preset:el('preset').value,submission_id:crypto.randomUUID()});el('lookup').value=data.task_id||'';el('message').textContent='Task submitted. Check its status below.';await refresh();}catch(e){el('message').textContent=e.message;}finally{el('submit').disabled=!verified;}});
function addLinks(value,label='Output'){if(typeof value==='string'&&value.startsWith('https://')){try{const u=new URL(value);if(u.username||u.password)return;const a=document.createElement('a');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent=`Open ${label.replaceAll('_',' ')}`;el('downloads').append(a);}catch{}}else if(value&&typeof value==='object'){for(const[k,v]of Object.entries(value))addLinks(v,k);}}
async function refresh(){const task=el('lookup').value.trim();if(!task){el('progress').textContent='Enter a task identifier.';return;}el('refresh').disabled=true;try{const d=await api('/api/task/'+encodeURIComponent(task));el('progress').textContent=`${d.status||'Status unknown'}${d.progress!==undefined?' · '+d.progress+'%':''}`;el('result').textContent=JSON.stringify(d,null,2);el('downloads').replaceChildren();addLinks(d.output);}catch(e){el('progress').textContent=e.message;}finally{el('refresh').disabled=false;}}
el('refresh').addEventListener('click',refresh);
api('/api/status').then(s=>{el('connection').textContent=s.key_configured?'KEY CONFIGURED · TEST CONNECTION':'API KEY NOT CONFIGURED';}).catch(()=>{el('connection').textContent='SERVER UNAVAILABLE';});fields();
